In [ ]:
walmart_store_locaction.csv

In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("Resources/walmart_store_locaction.csv.zip")

In [6]:
df.head()

,name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,fax_1,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,Conway Supercenter,https://www.walmart.com/store/5/conway-ar/details,1155 Hwy 65 North,Conway,AR,72032,US,501-329-0023,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.108660,-92.436905,NaN,NaN,NaN,NaN,NaN
1,Sikeston Supercenter,https://www.walmart.com/store/9/sikeston-mo/de...,1303 S Main St,Sikeston,MO,63801,US,573-472-3020,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.857394,-89.586051,NaN,NaN,NaN,NaN,NaN
2,Tahlequah Supercenter,https://www.walmart.com/store/10/tahlequah-ok/...,2020 S Muskogee Ave,Tahlequah,OK,74464,US,918-456-8804,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.888765,-94.979859,NaN,NaN,NaN,NaN,NaN
3,Mountain Home Supercenter,https://www.walmart.com/store/11/mountain-home...,65 Wal Mart Dr,Mountain Home,AR,72653,US,870-492-9299,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.354957,-92.341026,NaN,NaN,NaN,NaN,NaN
4,Claremore Supercenter,https://www.walmart.com/store/12/claremore-ok/...,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,918-341-2765,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.293955,-95.627125,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['name', 'url', 'street_address', 'city', 'state', 'zip_code', 'country',
       'phone_number_1', 'phone_number_2', 'fax_1', 'fax_2', 'email_1',
       'email_2', 'website', 'open_hours', 'latitude', 'longitude', 'facebook',
       'twitter', 'instagram', 'pinterest', 'youtube'],
      dtype='object')

In [10]:
walmart_locations_df=df.drop(columns=['name', 'url', 'phone_number_1', 'phone_number_2', 'fax_1', 'fax_2', 'email_1',
       'email_2', 'website', 'open_hours', 'facebook',
       'twitter', 'instagram', 'pinterest', 'youtube'], axis=1)

In [11]:
walmart_locations_df

,street_address,city,state,zip_code,country,latitude,longitude
0,1155 Hwy 65 North,Conway,AR,72032,US,35.108660,-92.436905
1,1303 S Main St,Sikeston,MO,63801,US,36.857394,-89.586051
2,2020 S Muskogee Ave,Tahlequah,OK,74464,US,35.888765,-94.979859
3,65 Wal Mart Dr,Mountain Home,AR,72653,US,36.354957,-92.341026
4,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,36.293955,-95.627125
...,...,...,...,...,...,...,...
4649,12631 Broadway Street,Pearland,TX,77584,US,29.556350,-95.415783
4650,1300 S Walton Blvd,Bentonville,AR,72712,US,36.357486,-94.214669
4651,3701 S Highland Dr,Millcreek,UT,84106,US,40.691031,-111.846529
4652,15757 Coit Rd,Dallas,TX,75248,US,32.963412,-96.770294
4653,5596 S Van Winkle Expy,Murray,UT,84117,US,40.649827,-111.849349

In [13]:
walmart_locations_df.isnull().sum()

street_address    0
city              0
state             0
zip_code          0
country           0
latitude          0
longitude         0
dtype: int64

In [14]:
walmart_locations_df.to_csv("Resources/walmart_locations.csv")